name: Publish provider packages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci +lint
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            fips: false
            image_repository: us-docker.pkg.dev/palette-images/edge/kairos-io
          - runner: ubuntu-24.04
            platform: linux/amd64
            fips: true
            image_repository: us-docker.pkg.dev/palette-images-fips/edge/kairos-io
          - runner: github-arm64-2c-8gb
            platform: linux/arm64
            fips: false
            image_repository: us-docker.pkg.dev/palette-images/edge/kairos-io
          - runner: github-arm64-2c-8gb
            platform: linux/arm64
            fips: true
            image_repository: us-docker.pkg.dev/palette-images-fips/edge/kairos-io
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: echo "${{ secrets.ARTIFACT_IMG_PUSH_EDGE }}" | base64 -d | docker login -u _json_key --password-stdin us-docker.pkg.dev
      - run: earthly --ci --push --output --platform=${{ matrix.platform }} +build-provider-package --IMAGE_REPOSITORY=${{ matrix.image_repository }} --FIPS_ENABLED=${{ matrix.fips }}
  push:
    needs: build
    strategy:
      matrix:
        include:
          - fips: false
            image_repository: us-docker.pkg.dev/palette-images/edge/kairos-io
          - fips: true
            image_repository: us-docker.pkg.dev/palette-images-fips/edge/kairos-io
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: echo "${{ secrets.ARTIFACT_IMG_PUSH_EDGE }}" | base64 -d | docker login -u _json_key --password-stdin us-docker.pkg.dev
      - run: earthly --ci --push --output +provider-package-merge --IMAGE_REPOSITORY=${{ matrix.image_repository }} --FIPS_ENABLED=${{ matrix.fips }}
